### ISSUE TITLE
Add -fPIC to build script?

### ISSUE THREAD

**Issue by guycohen** [ChristianBelloni/complex-bessel-rs#2]
Hi,

On some older systems, compilation will fail. This can be fixed with the following patch:

--- a/build.rs
+++ b/build.rs
@@ -34,6 +34,7 @@ pub fn main() {

         Command::new(GFORTRAN_NAME)
             .arg("-shared")
+                                               .arg("-fPIC")
             .arg("amos/amos_iso_c_fortran_wrapper.f90")
             .arg("amos/machine.for")
             .arg("amos/zbesh.for")

**Comment by ChristianBelloni** [comment]
Hi there, sorry for the delay, patched and shipped for 1.0.0, thanks for the heads up 👍🏻
